// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqN_xJyw56kxGKDxqJ_ABG5_MIDCxvNr0',
    appId: '1:208068920412:web:54fb5dfbe4e91648e51299',
    messagingSenderId: '208068920412',
    projectId: 'familybox-23dc1',
    authDomain: 'familybox-23dc1.firebaseapp.com',
    storageBucket: 'familybox-23dc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJ2I_VewAZVJp8B9AU4ZIcFzxReCexQQ',
    appId: '1:208068920412:android:62b2ecc5cf8f3ed1e51299',
    messagingSenderId: '208068920412',
    projectId: 'familybox-23dc1',
    storageBucket: 'familybox-23dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2ynmBskylBQP5vdJZ5QJNQZXv-L_tXw',
    appId: '1:208068920412:ios:13ba4c3d8310f4f0e51299',
    messagingSenderId: '208068920412',
    projectId: 'familybox-23dc1',
    storageBucket: 'familybox-23dc1.appspot.com',
    iosBundleId: 'com.example.familyBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2ynmBskylBQP5vdJZ5QJNQZXv-L_tXw',
    appId: '1:208068920412:ios:13ba4c3d8310f4f0e51299',
    messagingSenderId: '208068920412',
    projectId: 'familybox-23dc1',
    storageBucket: 'familybox-23dc1.appspot.com',
    iosBundleId: 'com.example.familyBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqN_xJyw56kxGKDxqJ_ABG5_MIDCxvNr0',
    appId: '1:208068920412:web:89c4ad6545add2f4e51299',
    messagingSenderId: '208068920412',
    projectId: 'familybox-23dc1',
    authDomain: 'familybox-23dc1.firebaseapp.com',
    storageBucket: 'familybox-23dc1.appspot.com',
  );
}
